const artisanCategories: Array<ArtisanCategoryObjProps> = [
  { id: "98767", profession: "Cleaner" },
  { id: "98765", profession: "Painter" },
  { id: "98764", profession: "Mechanic" },
  { id: "98769", profession: "Capenter" },
  { id: "98763", profession: "Plumber" },
  { id: "98762", profession: "Electrician" },
  { id: "98761", profession: "Carpenter" },
];

const FeaturedArtisansData: Array<ArtisansDataObjProps> = [
  {
    id: "9876",
    name: "Agyei Ipsum",
    rating: 4.0,
    image: require("../../assets/images/home/2.png"),
    profession: "Plumber",
    service: "Engine Catalyst Installation",
    verified: true,
    price: 500,
    otherServices: [
      "24 x 7 Services",
      "Eco-Friendly",
      "Fast Service",
      "Home Visits",
      "Active",
      "Office Visits",
    ],
    reviews: 20,
    gallery: [
      require("../../assets/images/artisanProflie/1.png"),
      require("../../assets/images/artisanProflie/2.png"),
      require("../../assets/images/artisanProflie/1.png"),
      require("../../assets/images/artisanProflie/2.png"),
    ],
    previousWorks: [
      {
        image: require("../../assets/images/artisanProflie/3.png"),
        price: 500,
        date: "17 Oct 2023",
        service: "Toilet Fix",
        clientPrdouct: "Toilet",
      },
      {
        image: require("../../assets/images/artisanProflie/3.png"),
        price: 500,
        date: "15 Oct 2023",
        service: "BathTub Fix",
        clientPrdouct: "BathTub",
      },
    ],
    city: "Asamankese",
    region: "Eastern Region",
    completedServices: [
      {
        id: "1",
        service: "Full Engine Repair",
        category: "Mechanic",
        minimumPrice: 500,
        maximumPrice: 650,
        image: require("../../assets/images/artisanProflie/1.png"),
      },
      {
        id: "2",
        service: "Full Engine Repair",
        category: "Mechanic",
        minimumPrice: 500,
        maximumPrice: 650,
        image: require("../../assets/images/artisanProflie/1.png"),
      },
      {
        id: "3",
        service: "Full Engine Repair",
        category: "Mechanic",
        minimumPrice: 500,
        maximumPrice: 650,
        image: require("../../assets/images/artisanProflie/1.png"),
      },
      {
        id: "4",
        service: "Full Engine Repair",
        category: "Mechanic",
        minimumPrice: 500,
        maximumPrice: 650,
        image: require("../../assets/images/artisanProflie/1.png"),
      },
      {
        id: "5",
        service: "Full Engine Repair",
        category: "Mechanic",
        minimumPrice: 500,
        maximumPrice: 650,
        image: require("../../assets/images/artisanProflie/1.png"),
      },
    ],
  },
  {
    id: "9875",
    name: "Kofi Batzu",
    rating: 2.0,
    image: require("../../assets/images/home/3.png"),
    profession: "Carpenter",
    service: "Wood work and stuff",
    verified: true,
    price: 500,
    otherServices: ["Fast Service", "Home Visits", "Active", "Office Visits"],
    reviews: 58,
    gallery: [
      require("../../assets/images/artisanProflie/1.png"),
      require("../../assets/images/artisanProflie/2.png"),
      require("../../assets/images/artisanProflie/1.png"),
      require("../../assets/images/artisanProflie/2.png"),
    ],
    previousWorks: [
      {
        image: require("../../assets/images/artisanProflie/3.png"),
        price: 500,
        date: "17 Oct 2023",
        service: "Roof Placement",
        clientPrdouct: "Duplex",
      },
      {
        image: require("../../assets/images/artisanProflie/3.png"),
        price: 500,
        date: "15 Oct 2023",
        service: "Table Repair",
        clientPrdouct: "Table",
      },
    ],
    city: "Sekondi-Takoradi",
    region: "Western Region",
    completedServices: [
      {
        id: "1",
        service: "Full Engine Repair",
        category: "Mechanic",
        minimumPrice: 500,
        maximumPrice: 650,
        image: require("../../assets/images/artisanProflie/1.png"),
      },
      {
        id: "2",
        service: "Full Engine Repair",
        category: "Mechanic",
        minimumPrice: 500,
        maximumPrice: 650,
        image: require("../../assets/images/artisanProflie/1.png"),
      },
      {
        id: "3",
        service: "Full Engine Repair",
        category: "Mechanic",
        minimumPrice: 500,
        maximumPrice: 650,
        image: require("../../assets/images/artisanProflie/1.png"),
      },
      {
        id: "4",
        service: "Full Engine Repair",
        category: "Mechanic",
        minimumPrice: 500,
        maximumPrice: 650,
        image: require("../../assets/images/artisanProflie/1.png"),
      },
      {
        id: "5",
        service: "Full Engine Repair",
        category: "Mechanic",
        minimumPrice: 500,
        maximumPrice: 650,
        image: require("../../assets/images/artisanProflie/1.png"),
      },
    ],
  },
  {
    id: "9874",
    name: "Bisa kede",
    rating: 3.0,
    image: require("../../assets/images/home/3.png"),
    profession: "Cleaner",
    service: "Clean Tables, Chairs, and stuff",
    verified: false,
    price: 50,
    otherServices: [
      "24 x 7 Services",
      "Eco-Friendly",
      "Fast Service",
      "Home Visits",
      "Active",
      "Office Visits",
    ],
    reviews: 100,
    gallery: [
      require("../../assets/images/artisanProflie/1.png"),
      require("../../assets/images/artisanProflie/2.png"),
      require("../../assets/images/artisanProflie/1.png"),
      require("../../assets/images/artisanProflie/2.png"),
    ],
    previousWorks: [
      {
        image: require("../../assets/images/artisanProflie/3.png"),
        price: 500,
        date: "17 Oct 2023",
        service: "BathTub Fix",
        clientPrdouct: "BatTub",
      },
      {
        image: require("../../assets/images/artisanProflie/3.png"),
        price: 500,
        date: "15 Oct 2023",
        service: "BathTub Fix",
        clientPrdouct: "BathTub",
      },
    ],
    city: "Saltpond",
    region: "Central Region",
    completedServices: [
      {
        id: "1",
        service: "Full Engine Repair",
        category: "Mechanic",
        minimumPrice: 500,
        maximumPrice: 650,
        image: require("../../assets/images/artisanProflie/1.png"),
      },
      {
        id: "2",
        service: "Full Engine Repair",
        category: "Mechanic",
        minimumPrice: 500,
        maximumPrice: 650,
        image: require("../../assets/images/artisanProflie/1.png"),
      },
      {
        id: "3",
        service: "Full Engine Repair",
        category: "Mechanic",
        minimumPrice: 500,
        maximumPrice: 650,
        image: require("../../assets/images/artisanProflie/1.png"),
      },
      {
        id: "4",
        service: "Full Engine Repair",
        category: "Mechanic",
        minimumPrice: 500,
        maximumPrice: 650,
        image: require("../../assets/images/artisanProflie/1.png"),
      },
      {
        id: "5",
        service: "Full Engine Repair",
        category: "Mechanic",
        minimumPrice: 500,
        maximumPrice: 650,
        image: require("../../assets/images/artisanProflie/1.png"),
      },
    ],
  },
  {
    id: "9873",
    name: "Kwame Eujene",
    rating: 4.0,
    image: require("../../assets/images/home/2.png"),
    profession: "Painter",
    service: "Paint Classrooms, Offices, and Others",
    verified: true,
    price: 200,
    otherServices: [
      "24 x 7 Services",
      "Eco-Friendly",
      "Fast Service",
      "Active",
      "Office Visits",
    ],
    reviews: 10,
    gallery: [
      require("../../assets/images/artisanProflie/1.png"),
      require("../../assets/images/artisanProflie/2.png"),
      require("../../assets/images/artisanProflie/1.png"),
      require("../../assets/images/artisanProflie/2.png"),
    ],
    previousWorks: [
      {
        image: require("../../assets/images/artisanProflie/3.png"),
        price: 500,
        date: "17 Oct 2023",
        service: "4x4 wall painting",
        clientPrdouct: "Aso Rock",
      },
      {
        image: require("../../assets/images/artisanProflie/3.png"),
        price: 500,
        date: "15 Oct 2023",
        service: "4x4 wall painting",
        clientPrdouct: "Aso Rock",
      },
    ],
    city: "Savelugu",
    region: "Nothern Region",
    completedServices: [
      {
        id: "1",
        service: "Full Engine Repair",
        category: "Mechanic",
        minimumPrice: 500,
        maximumPrice: 650,
        image: require("../../assets/images/artisanProflie/1.png"),
      },
      {
        id: "2",
        service: "Full Engine Repair",
        category: "Mechanic",
        minimumPrice: 500,
        maximumPrice: 650,
        image: require("../../assets/images/artisanProflie/1.png"),
      },
      {
        id: "3",
        service: "Full Engine Repair",
        category: "Mechanic",
        minimumPrice: 500,
        maximumPrice: 650,
        image: require("../../assets/images/artisanProflie/1.png"),
      },
      {
        id: "4",
        service: "Full Engine Repair",
        category: "Mechanic",
        minimumPrice: 500,
        maximumPrice: 650,
        image: require("../../assets/images/artisanProflie/1.png"),
      },
      {
        id: "5",
        service: "Full Engine Repair",
        category: "Mechanic",
        minimumPrice: 500,
        maximumPrice: 650,
        image: require("../../assets/images/artisanProflie/1.png"),
      },
    ],
  },
  {
    id: "9872",
    name: "Agyei Ipsum",
    rating: 1.0,
    image: require("../../assets/images/home/3.png"),
    profession: "Electrician",
    service: "Install Wires, GoTv, and Others",
    verified: false,
    price: 500,
    otherServices: [
      "24 x 7 Services",
      "Eco-Friendly",
      "Fast Service",
      "Home Visits",
    ],
    reviews: 70,
    gallery: [
      require("../../assets/images/artisanProflie/1.png"),
      require("../../assets/images/artisanProflie/2.png"),
      require("../../assets/images/artisanProflie/1.png"),
      require("../../assets/images/artisanProflie/2.png"),
    ],
    previousWorks: [
      {
        image: require("../../assets/images/artisanProflie/3.png"),
        price: 500,
        date: "17 Oct 2023",
        service: "Cable Installation",
        clientPrdouct: "DsTv",
      },
      {
        image: require("../../assets/images/artisanProflie/3.png"),
        price: 500,
        date: "15 Oct 2023",
        service: "Cable Installation",
        clientPrdouct: "GoTv",
      },
    ],
    completedServices: [
      {
        id: "1",
        service: "Full Engine Repair",
        category: "Mechanic",
        minimumPrice: 500,
        maximumPrice: 650,
        image: require("../../assets/images/artisanProflie/1.png"),
      },
      {
        id: "2",
        service: "Full Engine Repair",
        category: "Mechanic",
        minimumPrice: 500,
        maximumPrice: 650,
        image: require("../../assets/images/artisanProflie/1.png"),
      },
      {
        id: "3",
        service: "Full Engine Repair",
        category: "Mechanic",
        minimumPrice: 500,
        maximumPrice: 650,
        image: require("../../assets/images/artisanProflie/1.png"),
      },
      {
        id: "4",
        service: "Full Engine Repair",
        category: "Mechanic",
        minimumPrice: 500,
        maximumPrice: 650,
        image: require("../../assets/images/artisanProflie/1.png"),
      },
      {
        id: "5",
        service: "Full Engine Repair",
        category: "Mechanic",
        minimumPrice: 500,
        maximumPrice: 650,
        image: require("../../assets/images/artisanProflie/1.png"),
      },
    ],
  },
];

const BookingsData: Array<BookingsDataProps> = [
  {
    id: "98765",
    image: require("../../assets/images/artisanBookings/1.png"),
    service: "Radiator Flush",
    clientProduct: "Toyota Camry",
    status: "Pending",
    dateTime: "6 Dec, 2023 - 2:00pm",
    provider: FeaturedArtisansData[0],
    address: "45, Kofi Annan ST, Accra",
  },
  {
    id: "98764",
    image: require("../../assets/images/artisanBookings/1.png"),
    service: "Radiator Flush",
    clientProduct: "Toyota Camry",
    status: "Confirmed",
    dateTime: "6 Dec, 2023 - 2:00pm",
    provider: FeaturedArtisansData[2],
    address: "45, Kofi Annan ST, Accra",
  },
  {
    id: "98763",
    image: require("../../assets/images/artisanBookings/1.png"),
    service: "Radiator Flush",
    clientProduct: "Toyota Camry",
    status: "Cancelled",
    dateTime: "6 Dec, 2023 - 2:00pm",
    provider: FeaturedArtisansData[3],
    address: "45, Kofi Annan ST, Accra",
  },
  {
    id: "98762",
    image: require("../../assets/images/artisanBookings/1.png"),
    service: "Radiator Flush",
    clientProduct: "Toyota Camry",
    status: "Pending",
    dateTime: "6 Dec, 2023 - 2:00pm",
    provider: FeaturedArtisansData[1],
    address: "45, Kofi Annan ST, Accra",
  },
  {
    id: "98761",
    image: require("../../assets/images/artisanBookings/1.png"),
    service: "Radiator Flush",
    clientProduct: "Toyota Camry",
    status: "Cancelled",
    dateTime: "6 Dec, 2023 - 2:00pm",
    provider: FeaturedArtisansData[0],
    address: "45, Kofi Annan ST, Accra",
  },
  {
    id: "98760",
    image: require("../../assets/images/artisanBookings/1.png"),
    service: "Radiator Flush",
    clientProduct: "Toyota Camry",
    status: "Confirmed",
    dateTime: "6 Dec, 2023 - 2:00pm",
    provider: FeaturedArtisansData[0],
    address: "45, Kofi Annan ST, Accra",
  },
];

const ClientMessages: Array<ClientMessagesProps> = [
  {
    id: "98765",
    messages: [
      {
        id: "98765",
        text: "Good Morning",
        sender: "client",
        unread: true,
        time: Date.now(),
        parentId: "98765",
        type: "text",
      },
      {
        id: "98763",
        text: "Morning",
        sender: "artisan",
        unread: true,
        time: Date.now(),
        parentId: "98765",
        type: "text",
      },
      {
        id: "98365",
        text: "You good? I would like a mechanic for my car. It's broken",
        sender: "client",
        unread: true,
        time: Date.now(),
        parentId: "98765",
        type: "text",
      },
    ],
    artisan: FeaturedArtisansData[0],
  },
  {
    id: "98764",
    messages: [
      {
        id: "98765",
        text: "Good Morning",
        sender: "client",
        unread: false,
        time: Date.now(),
        parentId: "98764",
        type: "text",
      },
    ],
    artisan: FeaturedArtisansData[2],
  },
  {
    id: "98763",
    messages: [
      {
        id: "98765",
        text: "Good Morning",
        sender: "client",
        unread: true,
        time: Date.now(),
        parentId: "98763",
        type: "text",
      },
    ],
    artisan: FeaturedArtisansData[3],
  },
  {
    id: "98762",
    messages: [
      {
        id: "98765",
        text: "Good Morning",
        sender: "client",
        unread: true,
        time: Date.now(),
        parentId: "98762",
        type: "text",
      },
    ],
    artisan: FeaturedArtisansData[4],
  },
];

const currentDate = new Date(Date.now());

// please ignore this in production. use timestamp instead.
function timeToUse(date, month) {
  currentDate.setMonth(month);
  currentDate.setDate(date);
  const updatedDateMilliseconds = currentDate.getTime();
  return updatedDateMilliseconds;
}
const ArtisanPaymentHistory: Array<ArtisanPaymentDataProps> = [
  {
    id: "98765",
    clientName: "Kofi Batzu",
    paymentMethod: "cash",
    senderName: "Antonio Roberto",
    amount: 1500,
    serviceCharge: 193.3,
    paymentTime: Date.now(),
    refNumber: 4568900,
    paymentStatus: "success",
    image: require("../../assets/images/account/2.png"),
  },
  {
    id: "98763",
    clientName: "Kofi Batzu",
    paymentMethod: "mobileMoney",
    senderName: "Antonio Roberto",
    amount: 150,
    serviceCharge: 193.3,
    paymentTime: Date.now(),
    refNumber: 4568900,
    paymentStatus: "success",
    image: require("../../assets/images/account/2.png"),
  },
  {
    id: "98762",
    clientName: "Kofi Batzu",
    paymentMethod: "cash",
    senderName: "Antonio Roberto",
    amount: 1500,
    serviceCharge: 193.3,
    paymentTime: Date.now(),
    refNumber: 4568900,
    paymentStatus: "success",
    image: require("../../assets/images/account/2.png"),
  },
  {
    id: "98768",
    clientName: "Kofi Batzu",
    paymentMethod: "mobileMoney",
    senderName: "Antonio Roberto",
    amount: 200,
    serviceCharge: 193.3,
    paymentTime: timeToUse(currentDate.getDate() - 1, currentDate.getMonth()),
    refNumber: 4568900,
    paymentStatus: "success",
    image: require("../../assets/images/account/2.png"),
  },
  {
    id: "98767668",
    clientName: "Kofi Batzu",
    paymentMethod: "mobileMoney",
    senderName: "Antonio Roberto",
    amount: 200,
    serviceCharge: 193.3,
    paymentTime: timeToUse(currentDate.getDate(), currentDate.getMonth()),
    refNumber: 4568900,
    paymentStatus: "success",
    image: require("../../assets/images/account/2.png"),
  },
  {
    id: "9876768",
    clientName: "Kofi Batzu",
    paymentMethod: "mobileMoney",
    senderName: "Antonio Roberto",
    amount: 200,
    serviceCharge: 193.3,
    paymentTime: timeToUse(currentDate.getDate() - 2, currentDate.getMonth()),
    refNumber: 4568900,
    paymentStatus: "success",
    image: require("../../assets/images/account/2.png"),
  },
  {
    id: "8767668",
    clientName: "Kofi Batzu",
    paymentMethod: "mobileMoney",
    senderName: "Antonio Roberto",
    amount: 200,
    serviceCharge: 193.3,
    paymentTime: timeToUse(currentDate.getDate(), currentDate.getMonth()),
    refNumber: 4568900,
    paymentStatus: "success",
    image: require("../../assets/images/account/2.png"),
  },
  {
    id: "987065",
    clientName: "Kofi Batzu",
    paymentMethod: "mobileMoney",
    senderName: "Antonio Roberto",
    amount: 1500,
    serviceCharge: 193.3,
    paymentTime: Date.now(),
    refNumber: 4568900,
    paymentStatus: "success",
    image: require("../../assets/images/account/2.png"),
  },
];

const artisanRatings: Array<ArtisanRatingsProps> = [
  {
    id: "98765",
    image: require("../../assets/images/home/2.png"),
    rating: 4.5,
    review: "Good work. He is the real deal",
    firstName: "Mary",
    lastName: "Stewart",
  },
  {
    id: "98665",
    image: require("../../assets/images/home/2.png"),
    rating: 4.5,
    review: "He's done it again",
    firstName: "Mary",
    lastName: "Stew",
  },
  {
    id: "88765",
    image: require("../../assets/images/home/2.png"),
    rating: 4.5,
    review: "Good work",
    firstName: "Mary",
    lastName: "Stewart",
  },
  {
    id: "9b8765",
    image: require("../../assets/images/home/2.png"),
    rating: 0.5,
    review: "I hate this guy's work. He's the worst in all of mankind!!",
    firstName: "Timothy",
    lastName: "Stewart",
  },
  {
    id: "9a8765",
    image: require("../../assets/images/home/2.png"),
    rating: 4.5,
    review: "Good work. He is the real deal",
    firstName: "Mary",
    lastName: "Stewart",
  },
  {
    id: "9876nn5",
    image: require("../../assets/images/home/2.png"),
    rating: 4.5,
    review: "Good work. He is the real deal",
    firstName: "Mary",
    lastName: "Stewart",
  },
  {
    id: "9873365",
    image: require("../../assets/images/home/2.png"),
    rating: 4.5,
    review: "Good work. He is the real deal",
    firstName: "Mary",
    lastName: "Stewart",
  },
  {
    id: "9800765",
    image: require("../../assets/images/home/2.png"),
    rating: 4.5,
    review: "Good work. He is the real deal",
    firstName: "Mary",
    lastName: "Stewart",
  },
];

const ArtisanNewOrders: Array<ArtisanNewOrdersProp> = [
  {
    id: "23456",
    date: "10th May 2023",
    time: "10:00am",
    firstName: "Nana",
    lastName: "Binta",
    startingPrice: 500,
    price: 650,
    service: "Full Engine Repair",
    image: require("../../assets/images/dashboard/12.jpg"),
    address: "45 kofi Annan ST, Accra",
    comment:
      "I want you to clean my vehicle's cooling system of sediment and rust so as to loren ipsum domain las re de maclene",
  },
  {
    id: "23453",
    date: "10th May 2023",
    time: "10:00am",
    firstName: "Nana",
    lastName: "Binta",
    startingPrice: 500,
    price: 650,
    service: "Full Engine Repair",
    image: require("../../assets/images/dashboard/12.jpg"),
    address: "45 kofi Annan ST, Accra",
    comment:
      "I want you to clean my vehicle's cooling system of sediment and rust so as to loren ipsum domain las re de maclene",
  },
  {
    id: "222456",
    date: "10th May 2023",
    time: "10:00am",
    firstName: "Nana",
    lastName: "Binta",
    startingPrice: 500,
    price: 550,
    service: "Full Engine Repair",
    image: require("../../assets/images/dashboard/12.jpg"),
    address: "45 kofi Annan ST, Accra",
    comment:
      "I want you to clean my vehicle's cooling system of sediment and rust so as to loren ipsum domain las re de maclene",
  },
  {
    id: "56",
    date: "10th May 2023",
    time: "10:00am",
    firstName: "Nana",
    lastName: "Binta",
    startingPrice: 500,
    price: 650,
    service: "Full Engine Repair",
    image: require("../../assets/images/dashboard/12.jpg"),
    address: "45 kofi Annan ST, Accra",
    comment:
      "I want you to clean my vehicle's cooling system of sediment and rust so as to loren ipsum domain las re de maclene",
  },
  {
    id: "2300456",
    date: "10th May 2023",
    time: "10:00am",
    firstName: "Nana",
    lastName: "Binta",
    startingPrice: 500,
    price: 650,
    service: "Full Engine Repair",
    image: require("../../assets/images/dashboard/12.jpg"),
    address: "45 kofi Annan ST, Accra",
    comment:
      "I want you to clean my vehicle's cooling system of sediment and rust so as to loren ipsum domain las re de maclene",
  },
  {
    id: "234mm56",
    date: "10th May 2023",
    time: "10:00am",
    firstName: "Nana",
    lastName: "Binta",
    startingPrice: 500,
    price: 650,
    service: "Full Engine Repair",
    image: require("../../assets/images/dashboard/12.jpg"),
    address: "45 kofi Annan ST, Accra",
    comment:
      "I want you to clean my vehicle's cooling system of sediment and rust so as to loren ipsum domain las re de maclene",
  },
  {
    id: "2883456",
    date: "10th May 2023",
    time: "10:00am",
    firstName: "Nana",
    lastName: "Binta",
    startingPrice: 500,
    price: 650,
    service: "Full Engine Repair",
    image: require("../../assets/images/dashboard/12.jpg"),
    address: "45 kofi Annan ST, Accra",
    comment:
      "I want you to clean my vehicle's cooling system of sediment and rust so as to loren ipsum domain las re de maclene",
  },
];

const ArtisanJobs: Array<JobsProp> = [
  {
    id: "234q56",
    date: "10th May 2023",
    time: "10:00am",
    firstName: "Nana",
    lastName: "Binta",
    startingPrice: 500,
    price: 650,
    service: "Full Engine Repair",
    image: require("../../assets/images/dashboard/12.jpg"),
    status: "pending",
    clientRating: 3,
    clientData: {
      id: "555",
      firstName: "Nana",
      lastName: "Binta",
      image: require("../../assets/images/dashboard/13.jpg"),
      phoneNo: "+2348033226049",
    },
  },
  {
    id: "234p53",
    date: "10th May 2023",
    time: "10:00am",
    firstName: "Nana",
    lastName: "Binta",
    startingPrice: 500,
    price: 650,
    service: "Full Engine Repair",
    image: require("../../assets/images/dashboard/12.jpg"),
    status: "completed",
    clientRating: 5,
    clientData: {
      id: "554",
      firstName: "Nana",
      lastName: "Binta",
      image: require("../../assets/images/dashboard/13.jpg"),
      phoneNo: "+2348033226049",
    },
  },
  {
    id: "22245k6",
    date: "10th May 2023",
    time: "10:00am",
    firstName: "Nana",
    lastName: "Binta",
    startingPrice: 500,
    price: 550,
    service: "Full Engine Repair",
    image: require("../../assets/images/dashboard/12.jpg"),
    status: "completed",
    clientRating: 2,
    clientData: {
      id: "553",
      firstName: "Nana",
      lastName: "Binta",
      image: require("../../assets/images/dashboard/13.jpg"),
      phoneNo: "+2348033226049",
    },
  },
  {
    id: "56l",
    date: "10th May 2023",
    time: "10:00am",
    firstName: "Nana",
    lastName: "Binta",
    startingPrice: 500,
    price: 650,
    service: "Full Engine Repair",
    image: require("../../assets/images/dashboard/12.jpg"),
    status: "pending",
    clientRating: 2.5,
    clientData: {
      id: "552",
      firstName: "Nana",
      lastName: "Binta",
      image: require("../../assets/images/dashboard/13.jpg"),
      phoneNo: "+2348033226049",
    },
  },
  {
    id: "230045x",
    date: "10th May 2023",
    time: "10:00am",
    firstName: "Nana",
    lastName: "Binta",
    startingPrice: 500,
    price: 650,
    service: "Full Engine Repair",
    image: require("../../assets/images/dashboard/12.jpg"),
    status: "pending",
    clientRating: 1,
    clientData: {
      id: "551",
      firstName: "Nana",
      lastName: "Binta",
      image: require("../../assets/images/dashboard/13.jpg"),
      phoneNo: "+2348033226049",
    },
  },
  {
    id: "234mm5y",
    date: "10th May 2023",
    time: "10:00am",
    firstName: "Nana",
    lastName: "Binta",
    startingPrice: 500,
    price: 650,
    service: "Full Engine Repair",
    image: require("../../assets/images/dashboard/12.jpg"),
    status: "completed",
    clientRating: 3,
    clientData: {
      id: "550",
      firstName: "Nana",
      lastName: "Binta",
      image: require("../../assets/images/dashboard/13.jpg"),
      phoneNo: "+2348033226049",
    },
  },
  {
    id: "288345z",
    date: "10th May 2023",
    time: "10:00am",
    firstName: "Nana",
    lastName: "Binta",
    startingPrice: 500,
    price: 650,
    service: "Full Engine Repair",
    image: require("../../assets/images/dashboard/12.jpg"),
    status: "pending",
    clientRating: 4,
    clientData: {
      id: "549",
      firstName: "Nana",
      lastName: "Binta",
      image: require("../../assets/images/dashboard/13.jpg"),
      phoneNo: "+2348033226049",
    },
  },
];

const ArtisanBookings: Array<ArtisanBookingsProps> = [
  {
    id: "9876",
    firstName: "John",
    lastName: "Friday",
    bookDate: "15th August, 2023",
    bookTime: "2:00pm",
    updatedTime: Date.now(),
    image: require("../../assets/images/artisanProflie/1.png"),
    status: "pending",
    startingPrice: 500,
    price: 700,
    service: "Radiator Flush",
    paymentMethod: "offline",
    ongoing: true,
    clientData: {
      id: "555",
      firstName: "Nana",
      lastName: "Binta",
      image: require("../../assets/images/dashboard/13.jpg"),
      phoneNo: "+2348033226049",
    },
  },
  {
    id: "98766",
    firstName: "Adwoa",
    lastName: "Kofi",
    bookDate: "15th August, 2023",
    bookTime: "2:00pm",
    updatedTime: Date.now(),
    image: require("../../assets/images/artisanProflie/1.png"),
    status: "pending",
    startingPrice: 500,
    price: 700,
    service: "Vacuum Testing",
    paymentMethod: "online",
    clientData: {
      id: "544",
      firstName: "Nana",
      lastName: "Binta",
      image: require("../../assets/images/dashboard/13.jpg"),
      phoneNo: "+2348033226049",
    },
  },
  {
    id: "9876gg",
    firstName: "Nana",
    lastName: "Samantha",
    bookDate: "15th August, 2023",
    bookTime: "2:00pm",
    updatedTime: Date.now(),
    image: require("../../assets/images/artisanProflie/1.png"),
    status: "pending",
    startingPrice: 500,
    price: 700,
    service: "Break Repair",
    paymentMethod: "offline",
    clientData: {
      id: "525",
      firstName: "Nana",
      lastName: "Binta",
      image: require("../../assets/images/dashboard/13.jpg"),
      phoneNo: "+2348033226049",
    },
  },
  {
    id: "9a876",
    firstName: "John",
    lastName: "Friday",
    bookDate: "15th August, 2023",
    bookTime: "2:00pm",
    updatedTime: Date.now(),
    image: require("../../assets/images/artisanProflie/1.png"),
    status: "completed",
    startingPrice: 500,
    price: 700,
    service: "Radiator Flush",
    paymentMethod: "offline",
    clientRating: 2,
    paymentMade: true,
  },
  {
    id: "9b8766",
    firstName: "Adwoa",
    lastName: "Kofi",
    bookDate: "15th August, 2023",
    bookTime: "2:00pm",
    updatedTime: Date.now(),
    image: require("../../assets/images/artisanProflie/1.png"),
    status: "completed",
    startingPrice: 500,
    price: 700,
    service: "Vacuum Testing",
    paymentMethod: "online",
    clientRating: 3.5,
    paymentMade: false,
  },
  {
    id: "9c876gg",
    firstName: "Nana",
    lastName: "Samantha",
    bookDate: "15th August, 2023",
    bookTime: "2:00pm",
    updatedTime: Date.now(),
    image: require("../../assets/images/artisanProflie/1.png"),
    status: "completed",
    startingPrice: 500,
    price: 700,
    service: "Break Repair",
    paymentMethod: "offline",
    clientRating: 4,
    paymentMade: true,
  },
  {
    id: "9a876v",
    firstName: "John",
    lastName: "Friday",
    bookDate: "15th August, 2023",
    bookTime: "2:00pm",
    updatedTime: Date.now(),
    image: require("../../assets/images/artisanProflie/1.png"),
    status: "cancelled",
    startingPrice: 500,
    price: 700,
    service: "Radiator Flush",
    paymentMethod: "offline",
    clientRating: 2,
  },
  {
    id: "9b8766n",
    firstName: "Adwoa",
    lastName: "Kofi",
    bookDate: "15th August, 2023",
    bookTime: "2:00pm",
    updatedTime: Date.now(),
    image: require("../../assets/images/artisanProflie/1.png"),
    status: "cancelled",
    startingPrice: 500,
    price: 700,
    service: "Vacuum Testing",
    paymentMethod: "online",
    clientRating: 3.5,
  },
  {
    id: "9c876ggm",
    firstName: "Nana",
    lastName: "Samantha",
    bookDate: "15th August, 2023",
    bookTime: "2:00pm",
    updatedTime: Date.now(),
    image: require("../../assets/images/artisanProflie/1.png"),
    status: "cancelled",
    startingPrice: 500,
    price: 700,
    service: "Break Repair",
    paymentMethod: "offline",
    clientRating: 4,
  },
];

const ArtisanMessages: Array<ArtisanMessagesProps> = [
  {
    id: "4567",
    messages: [
      {
        id: "0987",
        sender: "artisan",
        time: Date.now(),
        unread: false,
        text: "Hello, thank you for booking our services. How can we help you?",
        parentId: "4567",
        type: "text",
      },
      {
        id: "0986",
        sender: "client",
        time: Date.now(),
        unread: true,
        text: "I would like to have two sections of data passed in 2.5 milliseconds",
        parentId: "4567",
        type: "text",
      },
    ],
    client: {
      id: "555",
      firstName: "Nana",
      lastName: "Binta",
      image: require("../../assets/images/dashboard/13.jpg"),
    },
  },
  {
    id: "4n567",
    messages: [
      {
        id: "0987",
        sender: "artisan",
        time: Date.now(),
        unread: false,
        text: "Hello, thank you for booking our services. How can we help you?",
        parentId: "4n567",
        type: "text",
      },
    ],
    client: {
      id: "554",
      firstName: "Nana",
      lastName: "Binta",
      image: require("../../assets/images/dashboard/13.jpg"),
    },
  },
  {
    id: "3",
    messages: [
      {
        id: "0987",
        sender: "artisan",
        time: Date.now(),
        unread: false,
        text: "Hello, thank you for booking our services. How can we help you?",
        parentId: "3",
        type: "text",
      },
    ],
    client: {
      id: "553",
      firstName: "Michael",
      lastName: "Amos",
      image: require("../../assets/images/dashboard/13.jpg"),
    },
  },
  {
    id: "2",
    messages: [
      {
        id: "0987",
        sender: "client",
        time: Date.now(),
        unread: true,
        text: "I want to know your price, Ragnar",
        parentId: "2",
        type: "text",
      },
    ],
    client: {
      id: "552",
      firstName: "Michael",
      lastName: "Amos",
      image: require("../../assets/images/dashboard/13.jpg"),
    },
  },
  {
    id: "1",
    messages: [
      {
        id: "0987",
        sender: "artisan",
        time: Date.now(),
        unread: false,
        text: "Hello, thank you for booking our services. How can we help you?",
        parentId: "1",
        type: "text",
      },
    ],
    client: {
      id: "551",
      firstName: "Michael",
      lastName: "Amos",
      image: require("../../assets/images/dashboard/13.jpg"),
    },
  },
];

const ArtisanSubscriptionHistory: Array<ArtisanPaymentHistoryProps> = [
  { id: "9876", time: Date.now(), price: 650, status: "active" },
  { id: "456", time: Date.now(), price: 650, status: "expired" },
  { id: "000", time: Date.now(), price: 650, status: "expired" },
  { id: "nnn", time: Date.now(), price: 650, status: "expired" },
  { id: "09889", time: Date.now(), price: 650, status: "expired" },
];

const artisanGallery = [
  require("../../assets/images/artisanProflie/1.png"),
  require("../../assets/images/artisanProflie/2.png"),
  require("../../assets/images/artisanProflie/1.png"),
  require("../../assets/images/artisanProflie/2.png"),
  require("../../assets/images/artisanProflie/1.png"),
  require("../../assets/images/artisanProflie/1.png"),
  require("../../assets/images/artisanProflie/1.png"),
  require("../../assets/images/artisanProflie/1.png"),
  require("../../assets/images/artisanProflie/1.png"),
];

const artisanEarnings: Array<ArtisanEarnings> = [
  {
    id: "1",
    firstName: "Nana",
    lastName: "Binta",
    price: 650,
    status: "awaiting",
    image: require("../../assets/images/artisanProflie/1.png"),
    date: Date.now(),
    service: "Full Engine Repair",
  },
  {
    id: "2",
    firstName: "Nana",
    lastName: "Binta",
    price: 650,
    status: "settled",
    image: require("../../assets/images/artisanProflie/1.png"),
    date: Date.now(),
    service: "Full Engine Repair",
  },
  {
    id: "3",
    firstName: "Nana",
    lastName: "Binta",
    price: 650,
    status: "settled",
    image: require("../../assets/images/artisanProflie/1.png"),
    date: Date.now(),
    service: "Full Engine Repair",
  },
];

const artisanDebts: Array<ArtisanDebts> = [
  {
    id: "1",
    firstName: "Friday",
    lastName: "Adeyanju",
    price: 650,
    status: "pending",
    image: require("../../assets/images/artisanProflie/1.png"),
    date: Date.now(),
    service: "Mechanic",
  },
  {
    id: "2",
    firstName: "Friday",
    lastName: "Adeyanju",
    price: 650,
    status: "paid",
    image: require("../../assets/images/artisanProflie/1.png"),
    date: Date.now(),
    service: "Mechanic",
  },
  {
    id: "3",
    firstName: "Friday",
    lastName: "Adeyanju",
    price: 650,
    status: "paid",
    image: require("../../assets/images/artisanProflie/1.png"),
    date: Date.now(),
    service: "Mechanic",
  },
  {
    id: "4",
    firstName: "Friday",
    lastName: "Adeyanju",
    price: 650,
    status: "paid",
    image: require("../../assets/images/artisanProflie/1.png"),
    date: Date.now(),
    service: "Mechanic",
  },
];

const artisanServices: Array<ArtisanServicesProps> = [
  {
    id: "1",
    service: "Full Engine Repair",
    category: "Mechanic",
    minimumPrice: 500,
    maximumPrice: 650,
    image: require("../../assets/images/artisanProflie/1.png"),
    features: [
      "24 x 7 Services",
      "Eco-Friendly",
      "Fast Service",
      "Home Visits",
      "Active",
      "Office Visits",
    ],
    status: "pending",
  },
  {
    id: "2",
    service: "Full Engine Repair",
    category: "Carpentry",
    minimumPrice: 500,
    maximumPrice: 650,
    image: require("../../assets/images/artisanProflie/1.png"),
    features: [
      "24 x 7 Services",
      "Eco-Friendly",
      "Fast Service",
      "Home Visits",
      "Active",
      "Office Visits",
    ],
    status: "pending",
  },
  {
    id: "3",
    service: "Full Engine Repair",
    category: "Mechanic",
    minimumPrice: 500,
    maximumPrice: 650,
    image: require("../../assets/images/artisanProflie/1.png"),
    features: [
      "24 x 7 Services",
      "Eco-Friendly",
      "Fast Service",
      "Home Visits",
      "Active",
      "Office Visits",
    ],
    status: "pending",
  },
  {
    id: "4",
    service: "Full Engine Repair",
    category: "AC Repairs",
    minimumPrice: 500,
    maximumPrice: 650,
    image: require("../../assets/images/artisanProflie/1.png"),
    features: [
      "24 x 7 Services",
      "Eco-Friendly",
      "Fast Service",
      "Home Visits",
      "Active",
      "Office Visits",
    ],
    status: "pending",
  },
  {
    id: "5",
    service: "Full Engine Repair",
    category: "Mechanic",
    minimumPrice: 500,
    maximumPrice: 650,
    image: require("../../assets/images/artisanProflie/1.png"),
    features: [
      "24 x 7 Services",
      "Eco-Friendly",
      "Fast Service",
      "Home Visits",
      "Active",
      "Office Visits",
    ],
    status: "pending",
  },
  {
    id: "6",
    service: "Full Engine Repair",
    category: "Mechanic",
    minimumPrice: 500,
    maximumPrice: 650,
    image: require("../../assets/images/artisanProflie/1.png"),
    features: [
      "24 x 7 Services",
      "Eco-Friendly",
      "Fast Service",
      "Home Visits",
      "Active",
      "Office Visits",
    ],
    status: "pending",
  },
  {
    id: "7",
    service: "Full Engine Repair",
    category: "Mechanic",
    minimumPrice: 500,
    maximumPrice: 650,
    image: require("../../assets/images/artisanProflie/1.png"),
    features: [
      "24 x 7 Services",
      "Eco-Friendly",
      "Fast Service",
      "Home Visits",
      "Active",
      "Office Visits",
    ],
    status: "pending",
  },
  {
    id: "8",
    service: "Full Engine Repair",
    category: "Electrician",
    minimumPrice: 500,
    maximumPrice: 650,
    image: require("../../assets/images/artisanProflie/1.png"),
    features: [
      "24 x 7 Services",
      "Eco-Friendly",
      "Fast Service",
      "Home Visits",
      "Active",
      "Office Visits",
    ],
    status: "pending",
  },
  {
    id: "9",
    service: "Full Engine Repair",
    category: "Upholstery",
    minimumPrice: 500,
    maximumPrice: 650,
    image: require("../../assets/images/artisanProflie/1.png"),
    features: [
      "24 x 7 Services",
      "Eco-Friendly",
      "Fast Service",
      "Home Visits",
      "Active",
      "Office Visits",
    ],
    status: "pending",
  },
  {
    id: "10",
    service: "Full Engine Repair",
    category: "Mechanic",
    minimumPrice: 500,
    maximumPrice: 650,
    image: require("../../assets/images/artisanProflie/1.png"),
    features: [
      "24 x 7 Services",
      "Eco-Friendly",
      "Fast Service",
      "Home Visits",
      "Active",
      "Office Visits",
    ],
    status: "approved",
  },
  {
    id: "11",
    service: "Full Engine Repair",
    category: "AC Repairs",
    minimumPrice: 500,
    maximumPrice: 650,
    image: require("../../assets/images/artisanProflie/1.png"),
    features: [
      "24 x 7 Services",
      "Eco-Friendly",
      "Fast Service",
      "Home Visits",
      "Active",
      "Office Visits",
    ],
    status: "rejected",
  },
  {
    id: "12",
    service: "Full Engine Repair",
    category: "Mechanic",
    minimumPrice: 500,
    maximumPrice: 650,
    image: require("../../assets/images/artisanProflie/1.png"),
    features: [
      "24 x 7 Services",
      "Eco-Friendly",
      "Fast Service",
      "Home Visits",
      "Active",
      "Office Visits",
    ],
    status: "rejected",
  },
  {
    id: "13",
    service: "Full Engine Repair",
    category: "Mechanic",
    minimumPrice: 500,
    maximumPrice: 650,
    image: require("../../assets/images/artisanProflie/1.png"),
    features: [
      "24 x 7 Services",
      "Eco-Friendly",
      "Fast Service",
      "Home Visits",
      "Active",
      "Office Visits",
    ],
    status: "rejected",
  },
  {
    id: "14",
    service: "Full Engine Repair",
    category: "Mechanic",
    minimumPrice: 500,
    maximumPrice: 650,
    image: require("../../assets/images/artisanProflie/1.png"),
    features: [
      "24 x 7 Services",
      "Eco-Friendly",
      "Fast Service",
      "Home Visits",
      "Active",
      "Office Visits",
    ],
    status: "pending",
  },
  {
    id: "15",
    service: "Full Engine Repair",
    category: "Mechanic",
    minimumPrice: 500,
    maximumPrice: 650,
    image: require("../../assets/images/artisanProflie/1.png"),
    features: [
      "24 x 7 Services",
      "Eco-Friendly",
      "Fast Service",
      "Home Visits",
      "Active",
      "Office Visits",
    ],
    status: "approved",
  },
  {
    id: "16",
    service: "Full Engine Repair",
    category: "Mechanic",
    minimumPrice: 500,
    maximumPrice: 650,
    image: require("../../assets/images/artisanProflie/1.png"),
    features: [
      "24 x 7 Services",
      "Eco-Friendly",
      "Fast Service",
      "Home Visits",
      "Active",
      "Office Visits",
    ],
    status: "approved",
  },
  {
    id: "17",
    service: "Full Engine Repair",
    category: "Mechanic",
    minimumPrice: 500,
    maximumPrice: 650,
    image: require("../../assets/images/artisanProflie/1.png"),
    features: [
      "24 x 7 Services",
      "Eco-Friendly",
      "Fast Service",
      "Home Visits",
      "Active",
      "Office Visits",
    ],
    status: "pending",
  },
  {
    id: "18",
    service: "Full Engine Repair",
    category: "Mechanic",
    minimumPrice: 500,
    maximumPrice: 650,
    image: require("../../assets/images/artisanProflie/1.png"),
    features: [
      "24 x 7 Services",
      "Eco-Friendly",
      "Fast Service",
      "Home Visits",
      "Active",
      "Office Visits",
    ],
    status: "pending",
  },
  {
    id: "19",
    service: "Full Engine Repair",
    category: "Mechanic",
    minimumPrice: 500,
    maximumPrice: 650,
    image: require("../../assets/images/artisanProflie/1.png"),
    features: [
      "24 x 7 Services",
      "Eco-Friendly",
      "Fast Service",
      "Home Visits",
      "Active",
      "Office Visits",
    ],
    status: "approved",
  },
  {
    id: "20",
    service: "Full Engine Repair",
    category: "Mechanic",
    minimumPrice: 500,
    maximumPrice: 650,
    image: require("../../assets/images/artisanProflie/1.png"),
    features: [
      "24 x 7 Services",
      "Eco-Friendly",
      "Fast Service",
      "Home Visits",
      "Active",
      "Office Visits",
    ],
    status: "rejected",
  },
];

export {
  artisanCategories,
  FeaturedArtisansData,
  BookingsData,
  ClientMessages,
  ArtisanPaymentHistory,
  artisanRatings,
  ArtisanNewOrders,
  ArtisanJobs,
  ArtisanBookings,
  ArtisanMessages,
  ArtisanSubscriptionHistory,
  artisanGallery,
  artisanEarnings,
  artisanDebts,
  artisanServices,
};
