const Regions = [
  { id: "1", abv: "ga", region: "Greater Accra" },
  { id: "2", abv: "nt", region: "Nothern Region" },
  { id: "3", region: "Upper East", abv: "ue" },
  { id: "4", region: "Upper West", abv: "uw" },
  { id: "5", region: "Ashanti", abv: "ash" },
  { id: "6", region: "Oti", abv: "oti" },
  { id: "7", region: "Volta", abv: "vol" },
  { id: "8", region: "Bono East", abv: "boe" },
  { id: "9", region: "Brong-Ahafo", abv: "aha" },
  { id: "10", region: "North East", abv: "nte" },
  { id: "11", region: "Savannah", abv: "sav" },
  { id: "12", region: "Western North", abv: "wn" },
  { id: "13", region: "Western Region", abv: "wes" },
  { id: "14", region: "Eastern Region", abv: "eas" },
  { id: "15", region: "Central Region", abv: "cen" },
  { id: "16", region: "Bono Region", abv: "bon" },
];

const Cities = [
  { id: "1", city: "Accra", reg: "ga" },
  { id: "2", city: "Achiaman", reg: "ga" },
  { id: "3", city: "Dome", reg: "ga" },
  { id: "4", city: "Gbawe", reg: "ga" },
  { id: "5", city: "Medina Estates", reg: "ga" },
  { id: "6", city: "Nungua", reg: "ga" },
  { id: "7", city: "Tema", reg: "ga" },
  { id: "8", city: "Teshi Old Town", reg: "ga" },
  //
  { id: "9", city: "Bawku", reg: "ue" },
  { id: "10", city: "Bolgatanga", reg: "ue" },
  { id: "999000", city: "Navrongo", reg: "ue" },
  //
  { id: "999001", city: "Wa", reg: "uw" },
  //
  { id: "999002", city: "Agogo", reg: "ash" },
  { id: "999001", city: "Ejura", reg: "ash" },
  { id: "999003", city: "Konongo", reg: "ash" },
  { id: "9990", city: "Kumasi", reg: "ash" },
  { id: "99001", city: "Mampong", reg: "ash" },
  { id: "999009001", city: "Mamponteng", reg: "ash" },
  { id: "995459001", city: "Obuasi", reg: "ash" },
  { id: "99..9001", city: "Tafo", reg: "ash" },
  //
  { id: "99..9601", city: "Anloga", reg: "vol" },
  { id: "99..9501", city: "Ho", reg: "vol" },
  { id: "99..9401", city: "Hohoe", reg: "vol" },
  { id: "99..9301", city: "Keta", reg: "vol" },
  { id: "99..9201", city: "Kpandu", reg: "vol" },
  //
  { id: "99..a201", city: "Berekum", reg: "aha" },
  { id: "99..s201", city: "Kintampo", reg: "aha" },
  { id: "99..d201", city: "Sunyani", reg: "aha" },
  { id: "99..f201", city: "Techiman", reg: "aha" },
  { id: "99..g201", city: "Wenchi", reg: "aha" },
  //
  { id: "99..g211", city: "Salaga", reg: "nt" },
  { id: "99..g221", city: "Savelugu", reg: "nt" },
  { id: "99..g231", city: "Tamale", reg: "nt" },
  { id: "98..g241", city: "Yendi", reg: "nt" },
  //
  { id: "97..g24", city: "Aburi", reg: "eas" },
  { id: "96..g2", city: "Akim Oda", reg: "eas" },
  { id: "95..g241", city: "Akwatia", reg: "eas" },
  { id: "94..g241", city: "Asamankese", reg: "eas" },
  { id: "93..g241", city: "Begoro", reg: "eas" },
  { id: "92..g241", city: "Koforidua", reg: "eas" },
  { id: "91..g241", city: "Nkawkaw", reg: "eas" },
  { id: "922..g241", city: "Nsawam", reg: "eas" },
  { id: "9933.g241", city: "Odumase Krobo", reg: "eas" },
  { city: "Suhum", reg: "eas" },
  //
  { city: "Axim", reg: "wes" },
  { city: "Bibiani", reg: "wes" },
  { city: "Prestea", reg: "wes" },
  { city: "Sekondi-Takoradi", reg: "wes" },
  { city: "Shama Junction", reg: "wes" },
  { city: "Takoradi", reg: "wes" },
  { city: "Tarkwa", reg: "wes" },
  { city: "Wassa-Akropong", reg: "wes" },
  //   { city: "Suhum", reg: "wes" },
  //
  { city: "Apam", reg: "cen" },
  { city: "Cape Coast", reg: "cen" },
  { city: "Dunkwa", reg: "cen" },
  { city: "Elmina", reg: "cen" },
  { city: "Foso", reg: "cen" },
  { city: "Kasoa", reg: "cen" },
  { city: "Mumford", reg: "cen" },
  { city: "Saltpond", reg: "cen" },
  { city: "Swedru", reg: "cen" },
  { city: "Winneba", reg: "cen" },
  //
];

export { Regions, Cities };
